<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106910" started-at="2020-06-25T22:07:41 IST" finished-at="2020-06-25T22:09:28 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106910" started-at="2020-06-25T22:07:41 IST" finished-at="2020-06-25T22:09:28 IST">
      <class name="com.ktpl.testcases.LoginpageTest">
        <test-method status="PASS" signature="initiateextentreports()[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="initiateextentreports" is-config="true" duration-ms="246" started-at="2020-06-25T22:07:41 IST" finished-at="2020-06-25T22:07:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateextentreports -->
        <test-method status="PASS" signature="initiate()[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="initiate" is-config="true" duration-ms="20398" started-at="2020-06-25T22:07:41 IST" finished-at="2020-06-25T22:08:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiate -->
        <test-method status="PASS" signature="LoginpagetitleTest()[pri:1, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="LoginpagetitleTest" duration-ms="645" started-at="2020-06-25T22:08:01 IST" finished-at="2020-06-25T22:08:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginpagetitleTest -->
        <test-method status="PASS" signature="extentteardown(org.testng.ITestResult)[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="extentteardown" is-config="true" duration-ms="1552" started-at="2020-06-25T22:08:02 IST" finished-at="2020-06-25T22:08:04 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginpagetitleTest status=SUCCESS method=LoginpageTest.LoginpagetitleTest()[pri:1, instance:com.ktpl.testcases.LoginpageTest@30b8a058] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentteardown -->
        <test-method status="PASS" signature="initiate()[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="initiate" is-config="true" duration-ms="19503" started-at="2020-06-25T22:08:04 IST" finished-at="2020-06-25T22:08:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiate -->
        <test-method status="FAIL" signature="CustomerloginTest()[pri:2, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="CustomerloginTest" duration-ms="12992" started-at="2020-06-25T22:08:23 IST" finished-at="2020-06-25T22:08:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login is not sucessfull expected [Home Page] but found [My Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login is not sucessfull expected [Home Page] but found [My Account]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.ktpl.testcases.LoginpageTest.CustomerloginTest(LoginpageTest.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CustomerloginTest -->
        <test-method status="PASS" signature="extentteardown(org.testng.ITestResult)[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="extentteardown" is-config="true" duration-ms="1775" started-at="2020-06-25T22:08:36 IST" finished-at="2020-06-25T22:08:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CustomerloginTest status=FAILURE method=LoginpageTest.CustomerloginTest()[pri:2, instance:com.ktpl.testcases.LoginpageTest@30b8a058] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentteardown -->
        <test-method status="PASS" signature="initiate()[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="initiate" is-config="true" duration-ms="18989" started-at="2020-06-25T22:08:38 IST" finished-at="2020-06-25T22:08:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiate -->
        <test-method status="FAIL" signature="forgotpasswordlinkTest()[pri:3, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="forgotpasswordlinkTest" duration-ms="1136" started-at="2020-06-25T22:08:57 IST" finished-at="2020-06-25T22:08:58 IST">
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element <span>...</span> is not clickable at point (590, 608). Other element would receive the click: <div class="modals-overlay" style="z-index: 9001;"></div>
  (Session info: chrome=83.0.4103.116)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'RAMMOHANN-PC', ip: '192.168.43.207', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\RAMMOH~1.NIM\AppDa...}, goog:chromeOptions: {debuggerAddress: localhost:51435}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 8fbf3df060ad4b23558ef4e350c5589a]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <span>...</span> is not clickable at point (590, 608). Other element would receive the click: <div class="modals-overlay" style="z-index: 9001;"></div>
  (Session info: chrome=83.0.4103.116)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'RAMMOHANN-PC', ip: '192.168.43.207', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\RAMMOH~1.NIM\AppDa...}, goog:chromeOptions: {debuggerAddress: localhost:51435}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 8fbf3df060ad4b23558ef4e350c5589a
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy11.click(Unknown Source)
at com.ktpl.pages.Loginpage.clickonforgotpasswordlink(Loginpage.java:42)
at com.ktpl.testcases.LoginpageTest.forgotpasswordlinkTest(LoginpageTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotpasswordlinkTest -->
        <test-method status="PASS" signature="extentteardown(org.testng.ITestResult)[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="extentteardown" is-config="true" duration-ms="1505" started-at="2020-06-25T22:08:58 IST" finished-at="2020-06-25T22:08:59 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=forgotpasswordlinkTest status=FAILURE method=LoginpageTest.forgotpasswordlinkTest()[pri:3, instance:com.ktpl.testcases.LoginpageTest@30b8a058] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentteardown -->
        <test-method status="PASS" signature="initiate()[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="initiate" is-config="true" duration-ms="18603" started-at="2020-06-25T22:08:59 IST" finished-at="2020-06-25T22:09:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiate -->
        <test-method status="PASS" signature="CreateaccountlinkTest()[pri:4, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="CreateaccountlinkTest" duration-ms="7776" started-at="2020-06-25T22:09:18 IST" finished-at="2020-06-25T22:09:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateaccountlinkTest -->
        <test-method status="PASS" signature="extentteardown(org.testng.ITestResult)[pri:0, instance:com.ktpl.testcases.LoginpageTest@30b8a058]" name="extentteardown" is-config="true" duration-ms="1680" started-at="2020-06-25T22:09:26 IST" finished-at="2020-06-25T22:09:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateaccountlinkTest status=SUCCESS method=LoginpageTest.CreateaccountlinkTest()[pri:4, instance:com.ktpl.testcases.LoginpageTest@30b8a058] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentteardown -->
      </class> <!-- com.ktpl.testcases.LoginpageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
